-- Create staging table for the homebuilder sales file if it does not exist
CREATE TABLE IF NOT EXISTS RHODES.STAGING_SALES.HOMEBUILDER_SALES_RAW (
    CONTRACT_ID VARCHAR
    ,COMMUNITY VARCHAR
    ,CITY VARCHAR
    ,REGION VARCHAR
    ,PLAN_NAME VARCHAR
    ,SQFT NUMBER
    ,BEDROOMS NUMBER
    ,BATHROOMS FLOAT
    ,BASE_PRICE NUMBER
    ,UPGRADE_AMOUNT NUMBER
    ,INCENTIVE_AMOUNT NUMBER
    ,CONTRACT_PRICE NUMBER
    ,CONTRACT_DATE DATE
    ,CLOSE_DATE DATE
    ,DAYS_TO_CLOSE NUMBER
    ,STATUS VARCHAR
    ,BUYER_SOURCE VARCHAR
    ,AGENT_COMMISSION NUMBER
    ,LOAN_TYPE VARCHAR
    ,SALES_CONSULTANT VARCHAR
);

-- Create staging table for the regional manager lookup file if it does not exist
CREATE TABLE IF NOT EXISTS RHODES.STAGING_SALES.REGIONAL_MANAGERS_RAW (
REGION VARCHAR
,REGIONAL_MANAGER VARCHAR
,SALES_TARGET_UNITS NUMBER
,MARGIN_TARGET_PCT FLOAT
);

-- Create staging csv file format if it does not exist - used when copying from file into table
CREATE OR REPLACE FILE FORMAT RHODES.STAGING_SALES.CSV_FMT
  TYPE = CSV
  PARSE_HEADER = TRUE
  FIELD_OPTIONALLY_ENCLOSED_BY = '"';

-- Truncate both tables to ensure a clean raw table and data is not duplicated
TRUNCATE TABLE RHODES.STAGING_SALES.HOMEBUILDER_SALES_RAW;
TRUNCATE TABLE RHODES.STAGING_SALES.REGIONAL_MANAGERS_RAW;

-- Copy into statements that copy raw staging files into the new created tables in staging SCHEMA
COPY INTO RHODES.STAGING_SALES.HOMEBUILDER_SALES_RAW
FROM @RHODES.STAGING_SALES.STG_SALES_RAW/Homebuilder_Sales.csv
FILE_FORMAT = (FORMAT_NAME = 'RHODES.STAGING_SALES.CSV_FMT')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO RHODES.STAGING_SALES.REGIONAL_MANAGERS_RAW
FROM @RHODES.STAGING_SALES.STG_SALES_RAW/Regional_Manager_Lookup.csv
FILE_FORMAT = (FORMAT_NAME = 'RHODES.STAGING_SALES.CSV_FMT')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;