[snowflake]
user = "DataEngineer"
password = "DataEngineerTest123"
account = "nucadtu-tm09013"
warehouse = "ANALYTICS_WH"
database = "RHODES"
schema = "PROD_SALES"

[openai]
api_key = "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"